name: Unity Android CI Build

on:
  push:
    branches: [ main ]    # main ブランチに push されたとき実行
  workflow_dispatch:      # Actions 画面から手動実行も可能

jobs:
  build-android:
    name: Build Android Player
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Git LFS 対応

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-
            Library-

      - name: Build Unity Project (Android)
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android           # Android ビルド
          unityVersion: 6000.0.48f1         # Unity バージョン指定

      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AndroidBuild
          path: build/                     # ビルド結果（APK または AAB）がここに出力
